name: 'DepSafe'
description: 'Send alerts or label prs when there is unsafe updates in a pull request'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: false
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  type:
    description: 'Please select between check_pr (checking only a new created pr) or check_all (check all opened prs in the repo)'
    required: true
  alert_type:
    description: 'You can alert developers by comment (leaving comments) and/or label (labelling prs)'
    required: true
runs:
  using: 'node16'
  main: 'binary/index.js'